import type { GameState } from "./types";

/**
 * Preset city archetypes for the "New Game" screen.
 * Each preset supplies a partial GameState that overrides the base defaults,
 * plus i18n keys for its name / tagline / description.
 */
export interface CityPreset {
  id: string;
  nameKey: string;      // dict key OR "pt||en" inline
  taglineKey: string;
  descriptionKey: string;
  difficulty: 1 | 2 | 3 | 4 | 5;
  accent: "primary" | "success" | "warning" | "danger" | "info";
  emoji: string;
  overrides: Partial<GameState>;
}

export const CITY_PRESETS: CityPreset[] = [
  {
    id: "nova_aurora",
    nameKey: "preset_nova_name",
    taglineKey: "preset_nova_tag",
    descriptionKey: "preset_nova_desc",
    difficulty: 2,
    accent: "primary",
    emoji: "🌇",
    overrides: {
      cityName: "Nova Aurora",
      population: 42_000,
      happiness: 62,
      approval: 55,
      unemployment: 7.4,
      businesses: 320,
      inflation: 3.2,
      treasury: 850_000,
      debt: 0,
      policies: { education: 50, health: 50, security: 50, transport: 40 },
      taxes: { income: 12, property: 6, business: 10 },
      infra: { waterCapacity: 200, energyCapacity: 300 },
    },
  },
  {
    id: "porto_meridiano",
    nameKey: "preset_porto_name",
    taglineKey: "preset_porto_tag",
    descriptionKey: "preset_porto_desc",
    difficulty: 2,
    accent: "info",
    emoji: "🏖️",
    overrides: {
      cityName: "Porto Meridiano",
      population: 28_000,
      happiness: 74,
      approval: 60,
      unemployment: 9.8,
      businesses: 210,
      inflation: 4.1,
      treasury: 620_000,
      debt: 120_000,
      policies: { education: 45, health: 55, security: 40, transport: 55 },
      taxes: { income: 10, property: 8, business: 8 },
      infra: { waterCapacity: 180, energyCapacity: 220 },
    },
  },
  {
    id: "vale_do_ferro",
    nameKey: "preset_vale_name",
    taglineKey: "preset_vale_tag",
    descriptionKey: "preset_vale_desc",
    difficulty: 4,
    accent: "warning",
    emoji: "🏭",
    overrides: {
      cityName: "Vale do Ferro",
      population: 68_000,
      happiness: 42,
      approval: 38,
      unemployment: 14.2,
      businesses: 480,
      inflation: 6.8,
      treasury: 380_000,
      debt: 900_000,
      policies: { education: 35, health: 40, security: 60, transport: 45 },
      taxes: { income: 15, property: 7, business: 14 },
      infra: { waterCapacity: 300, energyCapacity: 520 },
    },
  },
  {
    id: "serra_alta",
    nameKey: "preset_serra_name",
    taglineKey: "preset_serra_tag",
    descriptionKey: "preset_serra_desc",
    difficulty: 1,
    accent: "success",
    emoji: "⛰️",
    overrides: {
      cityName: "Serra Alta",
      population: 12_500,
      happiness: 78,
      approval: 70,
      unemployment: 5.5,
      businesses: 90,
      inflation: 2.4,
      treasury: 320_000,
      debt: 0,
      policies: { education: 55, health: 55, security: 45, transport: 35 },
      taxes: { income: 9, property: 5, business: 8 },
      infra: { waterCapacity: 100, energyCapacity: 120 },
    },
  },
  {
    id: "sao_vitor",
    nameKey: "preset_vitor_name",
    taglineKey: "preset_vitor_tag",
    descriptionKey: "preset_vitor_desc",
    difficulty: 5,
    accent: "danger",
    emoji: "🌆",
    overrides: {
      cityName: "Metrópole São Vitor",
      population: 185_000,
      happiness: 34,
      approval: 28,
      unemployment: 16.8,
      businesses: 1_240,
      inflation: 8.5,
      treasury: -180_000,
      debt: 2_400_000,
      policies: { education: 40, health: 45, security: 65, transport: 55 },
      taxes: { income: 18, property: 9, business: 16 },
      infra: { waterCapacity: 780, energyCapacity: 1_100 },
    },
  },
  // ============================================================
  // Região Metropolitana da GRANDE SANTO PAULO
  // Seis municípios interligados por conurbação, trens e Marginal.
  // Cada arquétipo traduz suas mecânicas únicas em overrides fortes
  // (impostos, políticas, infra, felicidade, negócios). Os slogans
  // satíricos e as descrições narrativas vivem no i18n.
  // ============================================================
  {
    id: "santo_paulo",
    nameKey: "preset_stpaulo_name",
    taglineKey: "preset_stpaulo_tag",
    descriptionKey: "preset_stpaulo_desc",
    difficulty: 5,
    accent: "danger",
    emoji: "🏛️",
    overrides: {
      cityName: "Santo Paulo",
      population: 240_000,
      happiness: 38,
      approval: 32,
      unemployment: 11.5,
      businesses: 1_680,
      inflation: 7.2,
      treasury: -220_000,
      debt: 3_100_000,
      policies: { education: 45, health: 48, security: 62, transport: 70 },
      taxes: { income: 18, property: 10, business: 17 },
      infra: { waterCapacity: 950, energyCapacity: 1_400 },
    },
  },
  {
    id: "santo_caetano_norte",
    nameKey: "preset_scnorte_name",
    taglineKey: "preset_scnorte_tag",
    descriptionKey: "preset_scnorte_desc",
    difficulty: 2,
    accent: "success",
    emoji: "🏘️",
    overrides: {
      cityName: "Santo Caetano do Norte",
      population: 16_500,
      happiness: 78,
      approval: 66,
      unemployment: 4.2,
      businesses: 220,
      inflation: 3.1,
      treasury: 1_450_000,
      debt: 0,
      policies: { education: 55, health: 78, security: 60, transport: 25 },
      taxes: { income: 11, property: 9, business: 9 },
      infra: { waterCapacity: 220, energyCapacity: 280 },
    },
  },
  {
    id: "santo_bernardo_field",
    nameKey: "preset_sbfield_name",
    taglineKey: "preset_sbfield_tag",
    descriptionKey: "preset_sbfield_desc",
    difficulty: 4,
    accent: "warning",
    emoji: "🚚",
    overrides: {
      cityName: "Santo Bernardo do Field",
      population: 118_000,
      happiness: 46,
      approval: 41,
      unemployment: 13.6,
      businesses: 860,
      inflation: 6.1,
      treasury: 480_000,
      debt: 1_250_000,
      policies: { education: 42, health: 45, security: 55, transport: 38 },
      taxes: { income: 14, property: 6, business: 16 },
      infra: { waterCapacity: 540, energyCapacity: 980 },
    },
  },
  {
    id: "sao_andre",
    nameKey: "preset_sandre_name",
    taglineKey: "preset_sandre_tag",
    descriptionKey: "preset_sandre_desc",
    difficulty: 3,
    accent: "info",
    emoji: "🏙️",
    overrides: {
      cityName: "São André",
      population: 62_000,
      happiness: 61,
      approval: 54,
      unemployment: 8.2,
      businesses: 540,
      inflation: 4.3,
      treasury: 620_000,
      debt: 340_000,
      policies: { education: 52, health: 55, security: 50, transport: 52 },
      taxes: { income: 13, property: 8, business: 12 },
      infra: { waterCapacity: 380, energyCapacity: 480 },
    },
  },
  {
    id: "noitedema",
    nameKey: "preset_noitedema_name",
    taglineKey: "preset_noitedema_tag",
    descriptionKey: "preset_noitedema_desc",
    difficulty: 5,
    accent: "danger",
    emoji: "🏭",
    overrides: {
      cityName: "Noitedema",
      population: 92_000,
      happiness: 30,
      approval: 24,
      unemployment: 15.4,
      businesses: 620,
      inflation: 7.8,
      treasury: 180_000,
      debt: 1_680_000,
      policies: { education: 32, health: 34, security: 68, transport: 30 },
      taxes: { income: 15, property: 5, business: 18 },
      infra: { waterCapacity: 420, energyCapacity: 760 },
    },
  },
  {
    id: "bemua",
    nameKey: "preset_bemua_name",
    taglineKey: "preset_bemua_tag",
    descriptionKey: "preset_bemua_desc",
    difficulty: 4,
    accent: "warning",
    emoji: "🚂",
    overrides: {
      cityName: "Bemuá",
      population: 78_000,
      happiness: 40,
      approval: 36,
      unemployment: 14.8,
      businesses: 310,
      inflation: 6.4,
      treasury: 260_000,
      debt: 780_000,
      policies: { education: 38, health: 40, security: 45, transport: 58 },
      taxes: { income: 12, property: 5, business: 15 },
      infra: { waterCapacity: 300, energyCapacity: 620 },
    },
  },
];

export function findPreset(id: string): CityPreset | undefined {
  return CITY_PRESETS.find((p) => p.id === id);
}
