/**
 * Definições de tours por seção do hub. Cada seção tem uma chave de
 * localStorage separada (só toca uma vez por navegador) e um conjunto
 * de passos que apontam para wrappers `data-tour="<section>-<slot>"`
 * declarados dentro de `GameShell.renderSection`.
 */
import {
  Landmark, Building2, Bus, Users, Vote, AlertTriangle, Hammer, CircleDollarSign,
} from "lucide-react";
import type { SectionTourConfig } from "./SectionTour";
import type { HubSection } from "./DashboardHub";

const KEY = (s: string) => `prefeito2026:sectionTour:${s}`;

export const SECTION_TOURS: Partial<Record<HubSection, SectionTourConfig>> = {
  finance: {
    storageKey: KEY("finance"),
    Icon: CircleDollarSign,
    accent: "emerald",
    headerLabel: { pt: "Guia — Finanças", en: "Guide — Finance" },
    steps: [
      { title: { pt: "Bem-vindo às Finanças", en: "Welcome to Finance" },
        body: { pt: "Aqui você acompanha caixa, dívida, razão fiscal e LRF. Vou mostrar cada bloco.",
                en: "Track cash, debt, fiscal ledger and LRF. Let me walk you through." } },
      { target: "fin-summary", placement: "bottom",
        title: { pt: "Resumo do mês", en: "Month summary" },
        body: { pt: "Receita e despesa do último tick, saldo em caixa, dívida, inflação e desemprego.",
                en: "Last tick's revenue/expenses, cash on hand, debt, inflation and unemployment." } },
      { target: "fin-actions", placement: "bottom",
        title: { pt: "Empréstimo & dívida", en: "Loans & debt" },
        body: { pt: "Empréstimo para curto prazo (juros pelo cenário) ou quitar dívida quando puder.",
                en: "Loans for short-term (interest depends on scenario) or pay down debt when possible." } },
      { target: "fin-ledger", placement: "top",
        title: { pt: "Razão fiscal", en: "Fiscal ledger" },
        body: { pt: "Decomposição de receitas (IPTU, ISS…) e despesas (educação, saúde, juros…) com drivers.",
                en: "Breakdown of revenues (IPTU, ISS…) and expenses (education, health, interest…) with drivers." } },
      { target: "fin-lrf", placement: "top",
        title: { pt: "LRF", en: "LRF" },
        body: { pt: "Semáforo com limites de folha (54% RCL), dívida e regra de ouro. Estouros abrem CPI.",
                en: "Traffic light for payroll (54% RCL), debt and golden rule. Breaches open CPI." } },
    ],
  },

  policies: {
    storageKey: KEY("policies"),
    Icon: Landmark,
    accent: "sky",
    headerLabel: { pt: "Guia — Políticas", en: "Guide — Policies" },
    steps: [
      { title: { pt: "Políticas públicas & tributos", en: "Public policy & taxes" },
        body: { pt: "Ajuste verbas setoriais, impostos, infraestrutura e sustentabilidade.",
                en: "Tune sectoral budgets, taxes, infrastructure and sustainability." } },
      { target: "pol-services", placement: "right",
        title: { pt: "Serviços públicos", en: "Public services" },
        body: { pt: "Cada slider é o % do orçamento em educação, saúde, segurança e transporte. Cortes derrubam felicidade; aumentos pressionam o caixa.",
                en: "Each slider is the budget share of education, health, security and transport. Cuts hurt happiness; boosts strain the treasury." } },
      { target: "pol-taxes", placement: "right",
        title: { pt: "Impostos", en: "Taxes" },
        body: { pt: "IPTU, ISS e impostos sobre pessoa jurídica. Muito alto: fuga de empresa e informalidade. Muito baixo: quebra o caixa.",
                en: "Property, service and business tax. Too high: business flight and informality. Too low: broke treasury." } },
      { target: "pol-infra", placement: "top",
        title: { pt: "Infraestrutura", en: "Infrastructure" },
        body: { pt: "Água e energia atendendo a demanda? Se não, apagões e racionamento derrubam aprovação. Expanda antes do gargalo.",
                en: "Water/energy meeting demand? If not, blackouts and rationing tank approval. Expand before the bottleneck." } },
      { target: "pol-env", placement: "top",
        title: { pt: "Meio ambiente", en: "Environment" },
        body: { pt: "Investimento em sustentabilidade reduz poluição e melhora qualidade do ar. Impacto lento mas cumulativo.",
                en: "Sustainability spend cuts pollution and lifts air quality. Slow but cumulative." } },
    ],
  },

  urbanism: {
    storageKey: KEY("urbanism"),
    Icon: Building2,
    accent: "amber",
    headerLabel: { pt: "Guia — Urbanismo", en: "Guide — Urbanism" },
    steps: [
      { title: { pt: "Plano diretor", en: "Master plan" },
        body: { pt: "Aqui mora o zoneamento, habitação, demografia, conflitos fundiários e favelas.",
                en: "Zoning, housing, demography, land conflicts and slums live here." } },
      { target: "urb-landuse", placement: "right",
        title: { pt: "Uso do solo", en: "Land use" },
        body: { pt: "Outorga onerosa, IPTU progressivo, ZEIS e mapa de risco. Ferramentas para conter especulação e proteger áreas frágeis.",
                en: "Outorga onerosa, progressive property tax, ZEIS and hazard map. Tools to curb speculation and protect fragile areas." } },
      { target: "urb-housing", placement: "top",
        title: { pt: "Habitação", en: "Housing" },
        body: { pt: "MCMV, aluguel social e regularização fundiária. Reduz déficit habitacional e informalidade.",
                en: "Public housing, social rent and land titling. Cuts housing deficit and informality." } },
      { target: "urb-demog", placement: "top",
        title: { pt: "Demografia", en: "Demography" },
        body: { pt: "Pirâmide etária e migração — norteia sua estratégia de longo prazo (creches vs. UBS geriátrica).",
                en: "Age pyramid and migration — steers long-term strategy (daycares vs. geriatric care)." } },
      { target: "urb-conflict", placement: "top",
        title: { pt: "Conflitos fundiários", en: "Land conflicts" },
        body: { pt: "Reintegração, mediação ou regularização. Escolha errada explode na imprensa.",
                en: "Eviction, mediation or titling. Wrong pick blows up in the press." } },
      { target: "urb-favela", placement: "top",
        title: { pt: "Favelas", en: "Slums" },
        body: { pt: "Urbanize áreas informais para reduzir pressão social e risco de desastre — custa caixa alto.",
                en: "Urbanize informal areas to cut social pressure and disaster risk — steep upfront cost." } },
    ],
  },

  mobility: {
    storageKey: KEY("mobility"),
    Icon: Bus,
    accent: "cyan",
    headerLabel: { pt: "Guia — Mobilidade", en: "Guide — Mobility" },
    steps: [
      { title: { pt: "Mobilidade, clima e saneamento", en: "Mobility, climate & sanitation" },
        body: { pt: "Modais de transporte, drenagem urbana e o Marco do Saneamento.",
                en: "Transit modes, urban drainage and the Sanitation Framework." } },
      { target: "mob-transport", placement: "right",
        title: { pt: "Transporte", en: "Transport" },
        body: { pt: "BRT, metrô, vans informais e Tarifa Zero. Cada escolha muda subsídio, farebox e tempo de commute.",
                en: "BRT, metro, informal vans and Zero Fare. Each choice moves subsidy, farebox and commute time." } },
      { target: "mob-climate", placement: "top",
        title: { pt: "Clima & drenagem", en: "Climate & drainage" },
        body: { pt: "Piscinões, obras de contenção e alerta de risco. Reduzem enchentes no verão.",
                en: "Detention basins, containment works and risk alerts. Cut summer floods." } },
      { target: "mob-sanit", placement: "top",
        title: { pt: "Saneamento (SNIS)", en: "Sanitation (SNIS)" },
        body: { pt: "Estatal vs. PPP, coleta e reciclagem. Impacto direto em saúde e mortalidade infantil.",
                en: "Public vs. PPP, collection and recycling. Direct impact on health and infant mortality." } },
    ],
  },

  society: {
    storageKey: KEY("society"),
    Icon: Users,
    accent: "violet",
    headerLabel: { pt: "Guia — Sociedade", en: "Guide — Society" },
    steps: [
      { title: { pt: "Sociedade e desigualdade", en: "Society and inequality" },
        body: { pt: "Justiça espacial, mobilidade social, educação intergeracional e economia informal.",
                en: "Spatial justice, social mobility, intergenerational education and informal economy." } },
      { target: "soc-wellbeing", placement: "right",
        title: { pt: "Bem-estar", en: "Wellbeing" },
        body: { pt: "Composição da felicidade por grupo social. Ajuda a ver qual base está sangrando aprovação.",
                en: "Happiness breakdown by social group. Shows which base is bleeding approval." } },
      { target: "soc-spatial", placement: "top",
        title: { pt: "Justiça espacial", en: "Spatial justice" },
        body: { pt: "Distância periferia↔centro para escola/UBS/emprego. Reduza para desbloquear mobilidade social.",
                en: "Periphery↔center distance to school/clinic/job. Shrink it to unlock social mobility." } },
      { target: "soc-education", placement: "top",
        title: { pt: "Educação", en: "Education" },
        body: { pt: "Árvore de programas (creche → EJA → técnico → universidade). Efeito só aparece com 1–2 mandatos.",
                en: "Program tree (daycare → adult ed → technical → university). Payoff over 1–2 terms." } },
      { target: "soc-informal", placement: "top",
        title: { pt: "Informalidade", en: "Informality" },
        body: { pt: "Camelódromos, MEI, fiscalização. Mão pesada esvazia praça; leniência traz reclamação de comércio formal.",
                en: "Street vendors, micro-entrepreneurs, enforcement. Heavy hand empties squares; leniency angers formal trade." } },
      { target: "soc-parallel", placement: "top",
        title: { pt: "Poder paralelo", en: "Parallel power" },
        body: { pt: "Milícia e crime organizado disputando território. Ignorar aumenta 'imposto' informal na população.",
                en: "Militias and organized crime disputing territory. Ignoring raises informal 'tax' on residents." } },
    ],
  },

  politics: {
    storageKey: KEY("politics"),
    Icon: Vote,
    accent: "rose",
    headerLabel: { pt: "Guia — Política", en: "Guide — Politics" },
    steps: [
      { title: { pt: "Câmara, gabinete e integridade", en: "Council, cabinet and integrity" },
        body: { pt: "Capital político, coalizão, assessores, corregedoria e corrupção.",
                en: "Political capital, coalition, advisors, oversight and corruption." } },
      { target: "pl-coalition", placement: "right",
        title: { pt: "Coalizão", en: "Coalition" },
        body: { pt: "Convide/exclua partidos, atenda grupos de interesse, peça verba federal, faça geminação de cidades e campanha.",
                en: "Invite/eject parties, address interest groups, request federal grants, sister-city and campaign." } },
      { target: "pl-legislature", placement: "top",
        title: { pt: "Câmara", en: "Council" },
        body: { pt: "55 vereadores, votação por projeto. Sem base, projetos caem — e você paga em capital político.",
                en: "55 seats, project-by-project votes. Without a base, bills fall — and you pay in political capital." } },
      { target: "pl-advisors", placement: "top",
        title: { pt: "Assessores", en: "Advisors" },
        body: { pt: "Contrate/demita ministros. Qualidade do assessor define qualidade do conselho no topo do painel.",
                en: "Hire/fire ministers. Advisor skill drives the advice quality shown at the top of the panel." } },
      { target: "pl-oversight", placement: "top",
        title: { pt: "Corregedoria", en: "Oversight" },
        body: { pt: "TCE, CGM, MP. Aumentam risco de flagra, mas protegem contra impeachment por descuido.",
                en: "Audit court, comptroller, prosecutor. Raise flagrancy risk but shield from careless impeachment." } },
      { target: "pl-corruption", placement: "top",
        title: { pt: "Corrupção", en: "Corruption" },
        body: { pt: "Rachadinha e propinas: ganho de curto prazo, risco de CPI e impeachment. Você foi avisado.",
                en: "Kickbacks and bribes: short-term gain, CPI and impeachment risk. Consider yourself warned." } },
    ],
  },

  crisis: {
    storageKey: KEY("crisis"),
    Icon: AlertTriangle,
    accent: "orange",
    headerLabel: { pt: "Guia — Crise & Mídia", en: "Guide — Crisis & Media" },
    steps: [
      { title: { pt: "Gestão de crise", en: "Crisis management" },
        body: { pt: "Desastres, eventos de massa e resposta à imprensa em um lugar só.",
                en: "Disasters, mass events and press response in one place." } },
      { target: "cr-disaster", placement: "right",
        title: { pt: "Desastres", en: "Disasters" },
        body: { pt: "Chuvas, deslizamentos, apagão. Aja rápido: cada mês de omissão vira uma manchete negativa.",
                en: "Floods, landslides, blackout. Act fast: each idle month becomes a bad headline." } },
      { target: "cr-mass", placement: "top",
        title: { pt: "Eventos de massa", en: "Mass events" },
        body: { pt: "Show, greve, manifestação. Autorizar, negociar ou reprimir — cada um mexe em grupos diferentes.",
                en: "Concerts, strikes, protests. Authorize, negotiate or repress — each moves different groups." } },
      { target: "cr-media", placement: "top",
        title: { pt: "Mídia & PiuPiu", en: "Media & PiuPiu" },
        body: { pt: "Trending topics, entrevistas coletivas, resposta a manchetes. Cuidado com o 'efeito manada'.",
                en: "Trending topics, press conferences, headline replies. Beware the herd effect." } },
    ],
  },

  build: {
    storageKey: KEY("build"),
    Icon: Hammer,
    accent: "teal",
    headerLabel: { pt: "Guia — Construir", en: "Guide — Build" },
    steps: [
      { title: { pt: "Catálogo de construção", en: "Construction catalog" },
        body: { pt: "Aqui está o catálogo informativo. O crescimento urbano é automático — quem molda a cidade são impostos, ZEIS e transporte.",
                en: "Informational catalog. Urban growth is automatic — taxes, ZEIS and transit shape the city." } },
    ],
  },

  bidding: {
    storageKey: KEY("bidding"),
    Icon: Hammer,
    accent: "fuchsia",
    headerLabel: { pt: "Guia — Licitações", en: "Guide — Biddings" },
    steps: [
      { title: { pt: "Licitações (Modo Prefeito)", en: "Biddings (Mayor Mode)" },
        body: { pt: "Lance obras públicas, receba propostas das empreiteiras, escolha entre preço baixo e reputação — o menor preço pode virar obra parada.",
                en: "Open public works, receive contractor bids, weigh price vs. reputation — lowest bid can become a stalled project." } },
    ],
  },
};
